const bancosVzla = [
  { value: "0102", label: "Banco de Venezuela" },
  { value: "0104", label: "Venezolano de Crédito" },
  { value: "0105", label: "Banco Mercantil" },
  { value: "0108", label: "Banco Provincial" },
  { value: "0114", label: "Bancaribe" },
  { value: "0115", label: "Banco Exterior" },
  { value: "0128", label: "Banco Caroní" },
  { value: "0134", label: "Banesco" },
  { value: "0137", label: "Banco Sofitasa" },
  { value: "0138", label: "Banco Plaza" },
  { value: "0146", label: "Banco de la Gente Emprendedora (BANGENTE)" },
  { value: "0151", label: "Banco Fondo Común (BFC)" },
  { value: "0156", label: "100% Banco" },
  { value: "0157", label: "DelSur Banco" },
  { value: "0163", label: "Banco del Tesoro" },
  { value: "0166", label: "Banco Agrícola de Venezuela" },
  { value: "0168", label: "Bancrecer" },
  { value: "0169", label: "Mi Banco" },
  { value: "0171", label: "Banco Activo" },
  { value: "0172", label: "Bancamiga" },
  { value: "0173", label: "Banco Internacional de Desarrollo" },
  { value: "0174", label: "Banplus" },
  { value: "0175", label: "Banco Bicentenario" },
  { value: "0176", label: "Banco de la Fuerza Armada Nacional Bolivariana (BANFANB)" },
  { value: "0191", label: "Banco Nacional de Crédito (BNC)" },
];

export default bancosVzla;